services:
  web:
    build: ./frontend
    container_name: catalogobulk_web
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: ./Backend
    container_name: catalogobulk_api_prod
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: catalogobulk_mongo_prod
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: catalogobulk_redis_prod

volumes:
  mongo_data: